on: push
name: Publish
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: ftp://austinhuang.staff.endl.site/
          ftp-username: austinhuang
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: stm
          git-ftp-args: "--all"
